export const DEVICE_STATES = Object.freeze({
  ACTIVE: "ACTIVE",
  GRACE_PERIOD: "GRACE_PERIOD",
  LOCKED: "LOCKED",
  TEMP_UNLOCK: "TEMP_UNLOCK",
  UNLOCK_PENDING: "UNLOCK_PENDING",
  OFFLINE_PENDING: "OFFLINE_PENDING",
  CONSENT_INVALID: "CONSENT_INVALID",
  RELEASE_PENDING: "RELEASE_PENDING",
  RELEASED: "RELEASED"
});

export const DEVICE_RELEASE_STATES = Object.freeze([
  DEVICE_STATES.RELEASE_PENDING,
  DEVICE_STATES.RELEASED
]);

export const isDeviceReleaseState = (state) => DEVICE_RELEASE_STATES.includes(state);

export const DEVICE_POLICY_KEYS = Object.freeze({
  EMI_PAID: "EMI_PAID",
  EMI_GRACE: "EMI_GRACE",
  EMI_LOCKED: "EMI_LOCKED",
  TEMP_UNLOCKED: "TEMP_UNLOCKED",
  CONSENT_INVALID: "CONSENT_INVALID"
});
